# Generated by Django 5.2.13 on 2026-09-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comfyui_url', models.CharField(default='http://127.0.0.1:8188', max_length=200)),
                ('threshold', models.FloatField(default=0.78)),
            ],
        ),
    ]
