# Generated by Django 5.2.13 on 2026-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='aitoolkit_cmd',
            field=models.CharField(default='python flux_train_ui.py', max_length=300),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='aitoolkit_port',
            field=models.PositiveIntegerField(default=7860),
        ),
    ]
