# Generated by Django 5.2.13 on 2026-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='negative',
            field=models.TextField(blank=True, default=''),
        ),
    ]
